apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: pds41s64e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pds41s64e-python 
  name: pds41s64e-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pds41s64e-python
    weight: 100 
