apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pds41s64e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pds41s64e-python 
  name: pds41s64e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pds41s64e-python 
